// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_Ag5d8OCy3CAg_bRCW8zKUShvKD1cZY',
    appId: '1:538278654073:web:e0ee9921152485378224a8',
    messagingSenderId: '538278654073',
    projectId: 'authfirebase-dbf0f',
    authDomain: 'authfirebase-dbf0f.firebaseapp.com',
    storageBucket: 'authfirebase-dbf0f.appspot.com',
    measurementId: 'G-QMD4J7ZSX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEs9V8TDTCGyGN62bGYpGoviLfI0Uiq0',
    appId: '1:538278654073:android:d26b95e6c795fdd88224a8',
    messagingSenderId: '538278654073',
    projectId: 'authfirebase-dbf0f',
    storageBucket: 'authfirebase-dbf0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdskTLXItgzJ1Uv2YHnQHOVX_0LOTciQE',
    appId: '1:538278654073:ios:687bf0d0119e40ce8224a8',
    messagingSenderId: '538278654073',
    projectId: 'authfirebase-dbf0f',
    storageBucket: 'authfirebase-dbf0f.appspot.com',
    iosClientId: '538278654073-h632jugb47gqj5a5gj0cd1h26il6q0s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdskTLXItgzJ1Uv2YHnQHOVX_0LOTciQE',
    appId: '1:538278654073:ios:66c38dda0a6c637d8224a8',
    messagingSenderId: '538278654073',
    projectId: 'authfirebase-dbf0f',
    storageBucket: 'authfirebase-dbf0f.appspot.com',
    iosClientId: '538278654073-evemrn94ld27bmoqk7n716qncvoq5q8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}
